mybatis:
  type-aliases-package: com.moon.model
  configuration:
    map-underscore-to-camel-case: true

spring:
  application:
    name: cloud-a
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/looking
    username: root
    password: macmysql


server:
  port: 8081
